### ISSUE TITLE
Window in the middle does not go away

### ISSUE THREAD

**Issue by javedbartlett** [belvederef/visual-snow-relief-overlay#5]
Window outline for the options menu doesn't go away after minimizing or pressing Cmd + alt + 0 on Mac OS Big Sur 11.1

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/48427864/108117721-e837a980-7062-11eb-9317-feccc68610fb.png">

**Comment by belvederef** [comment]
Thanks for flagging this up. Can you check whether the empty frame goes away once you click outside of it?

**Comment by javedbartlett** [comment]
> Thanks for flagging this up. Can you check whether the empty frame goes away once you click outside of it?

Can confirm it does not go away when clicking away

**Comment by belvederef** [comment]
What if you Alt+Tab? Not that you should need to do it to use the app, just trying to debug.

I will look into this, but to be fair the biggest challenge for me is to test it as I do not have a Mac. I will update here and would appreciate if you could help me test it.

**Comment by javedbartlett** [comment]
> What if you Alt+Tab? Not that you should need to do it to use the app, just trying to debug.
> 
> 
> 
> I will look into this, but to be fair the biggest challenge for me is to test it as I do not have a Mac. I will update here and would appreciate if you could help me test it.

Alt tab doesn't help either
